### ISSUE TITLE
[API] ID is limited to 50

### ISSUE THREAD

**Issue by MrYamous** [SignamarcheixH/javascript-workers#4]
The number of users is currently limited to 50, so requests should be limited to this id
<img width="181" alt="Capture d’écran 2019-12-05 à 11 07 07" src="https://user-images.githubusercontent.com/32437818/70227021-298bb400-1752-11ea-92a8-5a297899cdd6.png">

**Comment by SignamarcheixH** [comment]
Thanks MrYamous ! I was generating an random id up to 55 until now, but now that I've fixed it, everything should be working properly !
